Laboratory56/Laboratory56/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laboratory56.Data;
using Laboratory56.Models;
using Laboratory56.Models.AccountViewModels;
using Laboratory56.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace Laboratory56.Controllers
{
    public class ApplicationUsersController : Controller
    {
        #region Conect and ctor

        public ApplicationUsersController(
            ApplicationDbContext context, 
            IHostingEnvironment environment, 
            FileUploadService fileUploadService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _fileUploadService = fileUploadService;
            _userManager = userManager;
        }
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;
        

        #endregion

        #region AllUser

        public ActionResult UsersList()
        {
            return View(_context.Users.ToList());
        }

        #endregion

        #region Index

        // GET: ApplicationUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApplicationUser.ToListAsync());
        }

        #endregion

        #region Details

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser
                .SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }
        


        #endregion

        #region Create

        // GET: ApplicationUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,AvatarImage,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }
        

        #endregion

        #region Edit

        // GET: ApplicationUsers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,AvatarImage,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser, ApplicationUserVM model)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }
            var applicationUserList = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (ModelState.IsValid)
            {
                try
                {
                    var path = Path.Combine(
                        _environment.WebRootPath,
                        $"images\\{_userManager.GetUserName(User)}\\avatar");
                    _fileUploadService.Upload(path, model.AvatarImage.FileName, model.AvatarImage);
                    var avatarImageVar = $"images/{_userManager.GetUserName(User)}/avatar/{model.AvatarImage.FileName}";

                    applicationUserList.AvatarImage = avatarImageVar;
                    applicationUserList.UserName = applicationUser.UserName;
                    applicationUserList.Email = applicationUser.Email;
                    applicationUserList.PhoneNumber = applicationUser.PhoneNumber;


                    _context.Update(applicationUserList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }
        

        #endregion

        #region Delete

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser
                .SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }

        #endregion
    }
}

Laboratory56/Laboratory56/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Laboratory56.Data;
using Laboratory56.Models;
using Laboratory56.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace Laboratory56.Controllers
{
    public class CommentsController : Controller
    {
        #region Conection and ctor

        public CommentsController(ApplicationDbContext context, IHostingEnvironment environment,
            FileUploadService fileUploadService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _environment = environment;
            _fileUploadService = fileUploadService;
            _userManager = userManager;
        }

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;

        #endregion

        #region Index

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                var comments = await _context.Comments
                    .Include(c => c.User)
                    .Include(c => c.Post)
                    .Where(p => p.UserId == user.Id)
                    .OrderByDescending(c => c.PostId).ToListAsync();
                return View(comments);
            }
            else
            {
                var comments = await _context.Comments
                    .Include(c => c.User)
                    .Include(c => c.Post)
                    .OrderByDescending(c => c.PostId).ToListAsync();
                return View(comments);
            }
            
        }

        #endregion

        #region Details

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int id, PublicationVM model)
        {
            ViewBag.Comment = _context.Comments.Where(c => c.PostId == id);
           
            if (id == null)
            {
                return NotFound();
            }
            var comment = await _context.Comments
                .Include(c => c.Post)
                .Include(c => c.User)
                .SingleOrDefaultAsync(m => m.CommentId == id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        #endregion

        #region Create

// GET: Comments/Create
        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentId,PostId,CommentDate")] Comment comment)
        {
            var publ = _context.Publications.FirstOrDefault(c => c.Id == comment.PostId);
            if (publ != null) comment.ImageUrl = publ.ImageUrl;


            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(comment);
        }



        #endregion

        #region Edit


        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            /*if (id == null)
            {
                return NotFound();
            }*/

            var comment = await _context.Comments.SingleOrDefaultAsync(m => m.CommentId == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CommentId,PostId,CommentDate,Content")] Comment comment)
        {
            if (id != comment.CommentId)
            {
                return NotFound();
            }
            var searching = await _context.Comments.SingleOrDefaultAsync(s => s.CommentId == id);

            if (ModelState.IsValid)
            {
                try
                {
                    
                    searching.Content = comment.Content;

                    _context.Update(searching);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(comment);
        }

//        private bool CommentExists(int commentId)
//        {
//            throw new NotImplementedException();
//        }

        #endregion

        #region Delete

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            /*if (id == null)
            {
                return NotFound();
            }*/

            var comment = await _context.Comments
                .SingleOrDefaultAsync(m => m.CommentId == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

// POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comments.SingleOrDefaultAsync(m => m.CommentId == id);
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.CommentId == id);
        }

        #endregion

        #region Comment

        #region version 1

        [HttpPost]
        public async Task<IActionResult> Comment(int postId, string userId, string content, Comment comment)
        {
            var publ = _context.Publications.FirstOrDefault(c => c.Id == comment.PostId);
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var comm = new Comment
                {
                    UserId = userId,
                    PostId = postId,
                    Content = content,
                    ImageUrl = publ?.ImageUrl,
                    CommentDate = DateTime.Now
                };

                comm.UserId = user.Id;
                _context.Add(comm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        #endregion

        #region version 2

        /*[HttpPost]
        public async Task<IActionResult> Comment(int postId, string userId, string content, Comment comment)
        {
            var publ = _context.Publications.FirstOrDefault(c => c.Id == comment.PostId);

            if (publ == null) return NotFound();

            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var comm = new Comment
                {
                    UserId = userId,
                    PostId = postId,
                    Content = content,
//                    ImageUrl = publ != null ? publ.ImageUrl : null,
                    ImageUrl = publ.ImageUrl,
                    CommentDate = DateTime.Now
                };
                comm.UserId = user.Id;
                _context.Add(comm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }*/

        #endregion

        #endregion
    }
}

Laboratory56/Laboratory56/Views/Shared/_Layout.cshtml
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratory56</title>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Localizer["Laboratory56"]</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Publications" asp-action="Index">Мои публикации</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Searching">Поиск</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="UsersList">Все пользователи</a></li>
                        <li><a asp-area="" asp-controller="Comments" asp-action="Index">Мои комментарии</a></li>*@

                    <li>
                        <a asp-area="" asp-controller="Publications" asp-action="Index">@Localizer["Публикации"]</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Searching"> @Localizer["Поиск"]</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="UsersList"> @Localizer["Пользователи"]</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Comments" asp-action="Index"> @Localizer["Комментарии"]</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="GetCulture"> @Localizer["GetCulture"]</a>
                    </li>

                    @*<li>
                            <a href="/Publications/Index?culture=en">EN</a>
                        </li>
                        <li>
                            <a href="/Publications/Index?culture=ru">RU</a>
                        </li>*@
                    @*
                        <li>@Html.ActionLink(Laboratory56.Resources.HomeResurce.Мои_публикации, "Index", "Publications")</li>
                        <li>@Html.ActionLink(Laboratory56.Resources.HomeResurce.Поиск, "Searching", "Home")</li>
                        <li>@Html.ActionLink(Laboratory56.Resources.HomeResurce.Все_пользователи, "UsersList", "Home")</li>
                        <li>@Html.ActionLink(Laboratory56.Resources.HomeResurce.Мои_комментарии, "Index", "Comments")</li>*@



                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">

        <div>
            @await Html.PartialAsync("_SelectLanguagePartial") <br/> <hr/>
        </div>
        @RenderBody()
        <hr />

        <footer>
            <p>&copy; 2018 - Laboratory56</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Laboratory56/Laboratory56/Views/Shared/_PartialView.cshtml
@model Laboratory56.Models.Publication
@inject IViewLocalizer Localizer
<table class="table table-bordered">
    <thead>
    <tr>
        <th>
            @Localizer["Изображение"]
        </th>
        <th>
            @Localizer["Имя"]
        </th>
        <th>
            @Localizer["Описание"]
        </th>
        <th>
            @Localizer["Like"]
        </th>

    </tr>

    
    </thead>

    <tbody>
    <tr>
        <td>
            <a href="#" data-toggle="popover" data-trigger="hover" id="@Model.Id">
                <img src="~/@Model.ImageUrl" width="700" height="450"/>
            </a>
        </td>
        <td>

            <a asp-controller="ApplicationUsers" asp-action="Details" asp-route-id="@Model.User.Id" data-toggle="popover" data-trigger="hover" id="@Model.Id">@Model.User.Name</a>
            @* <a href="#" data-toggle="popover" data-trigger="hover" id="@Model.Id">@Model.User.Name</a> *@
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Like)
        </td>
    </tr>

    </tbody>

</table>

@*
    @if (Model.CommentsList.Count <= 0)
    {
        <tr>
            <td>
                No Comment
            </td>
        </tr>
    }
    else
    {
        foreach (var item in Model.CommentsList)
        {
            <a asp-controller="ApplicationUsers"
               asp-action="Details"
               asp-route-id="@item.User.Id">@item.User.Name:</a><p>@item.Content</p>
        }
    }
*@

<hr/>

@if (Model.CommentsList.Count <= 0)
{
    <tr>
        <td>
            No Comment
        </td>
    </tr>
}
else
{
    foreach (var item in Model.CommentsList)
    {
        <a asp-controller="ApplicationUsers"
           asp-action="Details"
           asp-route-id="@item.User.Id">
            @item.User.Name:
        </a>
        <p>@item.Content</p>
    }
}


<table>
    <tbody>
    <div class="row">
        <div class="col-lg-12">
            <a onclick="openCommentForm(@Model.Id)" style="cursor: pointer; color: darkslategray;">@Localizer["Оставить_комментарий"]</a>
        </div>
        <div class="col-md-12" id="postdiv-@Model.Id" style="display: none; color: darkslategray;">
            <textarea id="posttext-@Model.Id"></textarea> <br/>
            <input type="button" id="postComment" onclick="sendComment('@Model.Id', '@Model.UserId')" value=@Localizer["Отправить"]/>
        </div>
    </div>
    </tbody>
</table>
<br/>

<div id="postdiv-@Model.Id">

    <form>
        <input id="LikeId" type="button" value="Like" class="btn btn-default" onclick="sendLike('@Model.UserId', '@Model.Id')"
               style="color: aliceblue; background-color: darksalmon;"/>
        <input id="DisLikeId" type="button" value="Dislike" class="btn btn-default" onclick="sendDislike('@Model.UserId', '@Model.Id')"
               style="color: aliceblue; background-color: darksalmon;"/>

        <input id="subscribers-@Model.User" type="button" value="Subscribers" class="btn btn-default" onclick="SubScribers('@Model.UserId', '@Model.Id')"
               style="color: aliceblue; background-color: cadetblue;"/>

        @*<input id="unsubscribers-@Model.User" type="button" value="UnSubscribers" class="btn btn-default" onclick="UnSubScribers('@Model.UserId', '@Model.Id')"
            style="color: aliceblue; background-color: cadetblue;"/>*@
    </form>

</div>
<hr/>
<br/>


<script>
    function SubScribers(userId, postId) {
        $.ajax({
            url: '@Url.Action("SubscriptionMethod", "Publications")',
            type: 'POST',
            data: { 'userId': userId, 'postId': postId },
            success: function(data) {
                setTimeout(function() {
                        alert('Вы подписались :)', data)
                    },
                    100);
            },
            error: function() {
                console.log('Ошибка во время отправки комментария', this);
            }
        });
    }

    function UnSubScribers(userId, postId) {
        $.ajax({
            url: '@Url.Action("UnSubscriptionMethod", "Publications")',
            type: 'POST',
            data: { 'postId': postId, 'userId': userId },
            success: function(data) {
                setTimeout(function() {
                        alert('Вы отписались :(', data)
                    },
                    100);
            },
            error: function() {
                console.log('Ошибка во время отправки комментария', this);
            }
        });
    }

    function sendLike(userId, postId) {
        $.ajax({
            url: '@Url.Action("LikeMethod", "Publications")',
            type: 'POST',
            data: { 'postId': postId, 'userId': userId },
            success: function(data) {
                setTimeout(function() {
                        alert('Вы поставили Like!', data)
                    },
                    100);
            },
            error: function() {
                console.log('Ошибка во время отправки комментария', this);
            }
        });
    }

    function sendDislike(userId, postId) {
        $.ajax({
            url: '@Url.Action("DisLikeMethod", "Publications")',
            type: 'POST',
            data: { 'postId': postId, 'userId': userId },
            success: function(data) {
                setTimeout(function() {
                        alert('Вы поставили Disike!', data)
                    },
                    100);
            },
            error: function() {
                console.log('Ошибка во время отправки комментария', this);
            }
        });
    }


    function openCommentForm(postId) {
        $('#postdiv-' + postId).show();
    }

    function sendComment(postId, userId) {
        $.ajax({
            url: '@Url.Action("Comment", "Comments")',
            type: 'POST',
            data: { 'postId': postId, 'userId': userId, 'content': $('#posttext-' + postId).val() },
            success: function(data) {
                setTimeout(function() {
                        alert('Ваш комментарий ' + '(' + $('#posttext-' + postId).val() + ')' + ' добавлен!!!',
                            data)
                    },
                    100);
            },
            error: function() {
                console.log('Ошибка во время отправки комментария', this);
            }
        });
    }
</script>

Laboratory56/Laboratory56/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

@*<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    @Localizer["Language:"] <select name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"></select>
</form>*@

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    @Localizer["Language:"] <select name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"></select>
</form>